language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
before_script:
  - 'npm install'
script:
  - npm run test
  - npm run cover
after_success:
  - bash <(curl -s https://codecov.io/bash)